Date: 07/02/2019

In [1]:
import numpy as np

In [3]:
# Create a 1-D array by passing a list into NumPy's array() function.np.array([8, 4, 6, 0, 2])
np.array([8, 4, 6, 0, 2])

array([8, 4, 6, 0, 2])

In [4]:
print(np.array([1, 3, 5, 7, 9]))

[1 3 5 7 9]


In [5]:
#Create a 2-D array by passing a list of lists into array().
A = np.array( [ [1, 2, 3],[4, 5, 6] ] )
print(A)

[[1 2 3]
 [4 5 6]]


In [6]:
print(A[0,1], A[1,2])

2 6


In [7]:
A[0]

array([1, 2, 3])

### Problem 1

In [9]:
A = np.array([[3,-1,4], [1,5,-9]])
print(A)

[[ 3 -1  4]
 [ 1  5 -9]]


In [11]:
B = np.array([[2,6,-5,3],[5,-8,9,7], [9,-3,-2,-3]])
print(B)

[[ 2  6 -5  3]
 [ 5 -8  9  7]
 [ 9 -3 -2 -3]]


In [13]:
AB = np.dot(A, B)
print(AB)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


### Problem 2

In [16]:
A = np.array([[3,1,4], [1,5,9],[-5,3,1]])
print(A)

[[ 3  1  4]
 [ 1  5  9]
 [-5  3  1]]


In [19]:
A_new = -A^3 + 9*A^2 - 15*A
print(A_new)

[[ 54   0  29]
 [  0 124 216]
 [-98  54   0]]


In [30]:
np.full_like(A_new, 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

### Problem 3

In [135]:
A = np.triu(np.ones([7,7], dtype = 'int64'))
print(A)

[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]


In [137]:
B = np.triu(np.full_like(A, 5), 1) + np.tril(np.full_like(A, -1))
print(B)

[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]


In [138]:
ABA = A*B*A
print(ABA)

[[-1  5  5  5  5  5  5]
 [ 0 -1  5  5  5  5  5]
 [ 0  0 -1  5  5  5  5]
 [ 0  0  0 -1  5  5  5]
 [ 0  0  0  0 -1  5  5]
 [ 0  0  0  0  0 -1  5]
 [ 0  0  0  0  0  0 -1]]


In [140]:
ABA = ABA.astype(np.int64)

In [141]:
ABA.dtype

dtype('int64')

### Problem 4

In [98]:
x = np.arange(-100, 110, 10)
print(x)

[-100  -90  -80  -70  -60  -50  -40  -30  -20  -10    0   10   20   30   40
   50   60   70   80   90  100]


In [114]:
mask = x < 0 
x[mask]
print(x)

[  0   0   0   0   0   0   0   0   0   0   0  10  20  30  40  50  60  70
  80  90 100]


### Problem 5

In [179]:
A = np.array([[0,2,4],[1,3,5]])
B = np.tril(np.full((3,3),3))
C = np.eye(3, dtype = 'int64')*(-2)
print(A)
print(B)
print(C)

[[0 2 4]
 [1 3 5]]
[[3 0 0]
 [3 3 0]
 [3 3 3]]
[[-2  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [160]:
I = np.eye(3, dtype = 'int64')
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [161]:
A_trans = A.T
print(A.T)

[[0 1]
 [2 3]
 [4 5]]


In [187]:
a1 = np.column_stack((np.zeros(3), A_trans, I))
a2 = np.column_stack((A, np.zeros((2,2)), np.zeros(2)))
a3 = np.column_stack((B, C))

In [192]:
a3.shape

(3, 6)

In [193]:
np.vstack((a1,a2,a3))

array([[ 0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.],
       [ 3.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0., -2.]])

### Problem 6

In [214]:
A = np.array([[0,2,4],[1,3,5]])
print(A)

[[0 2 4]
 [1 3 5]]


In [216]:
def row_stochastic(x):
    return(x/x.sum(axis = 1).reshape((-1,1)))

In [217]:
A_new = row_stochastic(A)
print(A_new)

[[ 0.          0.33333333  0.66666667]
 [ 0.11111111  0.33333333  0.55555556]]


### Problem 7

In [228]:
import os
path = '/Users/Alina/Documents/GitHub/BootCamp2019/ProblemSets'
os.chdir(path)

In [230]:
grid = np.load("grid.npy")
print(grid)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 33 67 46 55 12 32 63 93

In [275]:
h_vert = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])

In [271]:
v_max = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])

In [272]:
ld_max = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])

In [273]:
rd_max = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])

In [277]:
winner = np.max([h_vert, v_max, ld_max, rd_max])
print(winner)

70600674
